### PR TITLE
Backport/feature/refactor scheduled jobs

### PR DESCRIPTION
**Pull request by armandfardeau**

### CODE REVIEW

**Comment by Quentinchampenois** [comment]
Hi, could you take a look at the last failing test ?
Thank you

**Comment by Quentinchampenois** [comment]
@armandfardeau Pull request still needed ?

**Comment by armandfardeau** [comment]
@paulinebessoles

**Comment by Quentinchampenois** [comment]
PR pending, closing it. Feel free to open it if still needed

**Pull request closed without merging**
